<?php

/**
 * @file
 * Contains premiumcontact.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function premiumcontact_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the premiumcontact module.
    case 'help.page.premiumcontact':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allow you to manage your contacts') . '</p>';
      return $output;

    default:
  }
}
