premium:
  name: 'Dupont Duval'
  message: 'Welcome on your Premium custum site'
_core:
  default_config_hash: 5lyewdTMTx6utCvR9A-EE3VXVIYCjyioLSQSaKVYJmI
message: 'Coucou. ça va les terriens?'
premium_cache:
  message: 'Hello les lolos! oh zut et encore'
  image: {  }
