schemas:
  bootstrap: 8000
  premiumTheme: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://127.0.0.1:8088/themes/custom/premiumTheme/favicon.ico'
  use_default: 1
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: ''
  url: ''
  use_default: 1
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
  footer_top: ''
table_responsive: '-1'
table: ''
copyright_holder: efe
