<?php

/**
 * Implements hook_block_view_BASE_BLOCK_ID_ALTER().
 */

function premium_block_view_premium_status_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block)
{
    $build['#pre_render'][] = '_premium_block_premium_prerender';

   // kint($block);
}

function _premium_block_premium_prerender(array $build)
{
    $build['content']['#prefix'] = '<h4>';
    $build['content']['#suffix'] = '</h4>';
    $build['content']['#markup'] = 'Mon message modifié';
    return $build;
}

/**
 * Implements hook_theme().
 */
function premium_theme($existing, $type, $theme, $path)
{
    $variables = array(
        'amIPremium' => array(
            'variables' => array(
                'message' => NULL,
                'color' => NULL,
            ),
            'template' => 'amIPremium',
        ),
    );
    return $variables;
}

/**
 * Implements hook_user_login().
 */
function premium_user_login($account)
{
    $config = \Drupal::config('premium.settings');
    drupal_set_message(t('@message', array(
        '@message' => $config->get('message'),
        )
    ));   

}

function _custom_theme($existing, $type, $theme, $path)
{
    $variables = array(
        'block--premium-cache' => array(
            'variables' => array(
                'message' => NULL,
                'image' => NULL,
            ),
            'template' => 'block--premium-cache',
        ),
    );
    return $variables;
}

function premium_preprocess_field(&$variables) 
{
    
  //  $config =  \Drupal::config('premium.settings');
    $field =  $variables['element'];
    if ($field['#field_name'] === 'field_promotion') {
       $config = \Drupal::config('premium.settings');
       // ksm($variables['items']);
        $variables['promotion'] = $variables['items'][0]['content']['#text'];
       // ksm($variables['promotion']);
        $variables['promotion'] = $config->get('premium_promotion.message');
       // ksm($variables['promotion']);
  }
    return $variables;

}